"""Player implementations and decision policies."""

from .heuristic_evaluator import (
    ActionFeatures,
    CardAcquisitionWeights,
    CardConstraintWeights,
    HeuristicWeights,
)
from .heuristic_player import HeuristicPlayer
from .random_player import RandomPlayer
from .state_evaluator import StateRewardWeights
from .card_value_shaping import (
    deck_card_ids,
    deck_value_potential,
    deckbuilding_shaping_delta,
    is_deckbuilding_action,
    load_card_values,
)
from .action_representation import (
    ACTION_REPRESENTATION_SCHEMA_VERSION,
    ActionRepresentation,
    representation_for_action,
    representation_for_neural_action,
)
from .imitation_dataset import (
    DATASET_SCHEMA_VERSION,
    DatasetCampaignConfig,
    DatasetGenerationResult,
    MatchupSpec,
    default_matchups,
    generate_dataset,
)
from .league_dataset import (
    LeagueDatasetConfig,
    LeagueDatasetResult,
    LeaguePlayerSpec,
    collect_league_dataset,
)
from .card_representation import (
    CARD_REPRESENTATION_SCHEMA_VERSION,
    CardSemanticRepresentation,
    ChampionAbilityRepresentation,
    EffectRepresentation,
    EffectStepRepresentation,
    OperationRepresentation,
    clear_representation_cache,
    representation_for_definition,
)
from .neural_model import (
    ContextualNeuralActionScorer,
    NeuralActionScorer,
    NeuralModelConfig,
    SemanticIdentityNeuralActionScorer,
    SUPPORTED_ARCHITECTURES,
    build_neural_scorer,
    migrate_v004_checkpoint_to_deck_state,
    migrate_v005_deck_state_checkpoint_to_tactical,
)
from .structured_v004 import StructuredSemanticCardEncoder, StructuredSemanticV4Scorer
from .structured_v005 import StructuredSemanticV5DeckStateScorer, StructuredSemanticV5FusionScorer
from .structured_v006 import StructuredSemanticV6TacticalActionScorer
from .neural_player import NeuralPlayer
from .player_factory import (
    MACRO_ARCHITECTURE_SCHEMA_VERSIONS,
    build_neural_player,
    is_macro_architecture,
)
from .macro_player import AtomicDecisionPayload, MacroDecisionPayload, MacroNeuralPlayer
from .macro_imitation_dataset import (
    MACRO_CANDIDATE_SCHEMA_VERSION,
    MACRO_DATASET_SCHEMA_VERSION,
    MacroDatasetCampaignConfig,
    MacroDatasetGenerationResult,
    generate_macro_dataset,
    heuristic_macro_selector,
)
from .macro_model import (
    MACRO_ARCHITECTURE,
    MACRO_V2_ARCHITECTURE,
    MACRO_V3_ARCHITECTURE,
    MACRO_V4_ARCHITECTURE,
    MacroActionScorer,
    MacroActionScorerV2,
    MacroActionScorerV3,
    MacroActionScorerV4,
    macro_candidate_from_dict,
)
from .macro_training import (
    MacroEvaluationMetrics,
    MacroTrainingMetrics,
    evaluate_macro_epoch,
    macro_imitation_loss,
    macro_record_diagnostics,
    macro_records,
    unified_record_diagnostics,
    unified_records,
    train_macro_epoch,
)
from .play_turn_solver import (
    DependencyDescriptor,
    MacroActionRepresentation,
    PlayTurnCandidate,
    PlayTurnOutcomeSummary,
    PlayTurnResolution,
    PlayTurnSolver,
    dependency_for_action,
    macro_representations_v3,
    macro_representations_v4,
)
from .composed_player import (
    HybridPlayer,
    DecisionDiagnostic,
    DeterministicBanishPolicy,
    HeuristicPlayPolicy,
    NeuralAcquisitionPolicy,
    build_composed_player,
    build_hybrid_player,
)
from .algorithmic_play import AlgorithmicPlayPolicy, PlayCardClassification
from .player_middleware import LegacyActionMiddleware, is_modern_player
from .hybrid_profiles import DEFAULT_HYBRID_PROFILE_DIR, HybridProfile, load_hybrid_profile
from .neural_training_profiles import (
    NeuralProfile,
    NeuralTrainingProfile,
    load_active_neural_profile,
    load_active_training_profile,
    load_training_profile,
    next_training_profile_id,
    save_training_profile,
    versioned_training_profiles,
)
from .neural_training import (
    TrainingMetrics,
    chosen_action_loss,
    combined_imitation_loss,
    iter_jsonl_records,
    EvaluationMetrics,
    evaluate_epoch,
    normalized_score_regression_loss,
    observation_from_dict,
    is_targeted_mercenary_record,
    pairwise_ranking_loss,
    seed_training,
    split_for_game_id,
    train_epoch,
    train_jsonl,
)
from .rl_training import (
    NeuralActorCritic,
    PPOTrainingMacroPlayer,
    PPOTrainingPlayer,
    PPOUpdateMetrics,
    RolloutResult,
    RolloutTransition,
    choose_opponent,
    collect_rollout,
    evaluate_greedy_model,
    gae_returns,
    is_monotonic_evaluation_improvement,
    ppo_update,
    terminal_reward,
    weighted_evaluation_score,
)
from .neural_reporting import load_metrics, write_training_report

__all__ = [
    "ActionFeatures",
    "ACTION_REPRESENTATION_SCHEMA_VERSION",
    "ActionRepresentation",
    "DATASET_SCHEMA_VERSION",
    "DatasetCampaignConfig",
    "DatasetGenerationResult",
    "CARD_REPRESENTATION_SCHEMA_VERSION",
    "CardAcquisitionWeights",
    "CardConstraintWeights",
    "CardSemanticRepresentation",
    "ChampionAbilityRepresentation",
    "EffectRepresentation",
    "EffectStepRepresentation",
    "HeuristicPlayer",
    "HeuristicWeights",
    "RandomPlayer",
    "StateRewardWeights",
    "deck_card_ids",
    "deck_value_potential",
    "deckbuilding_shaping_delta",
    "is_deckbuilding_action",
    "load_card_values",
    "MatchupSpec",
    "default_matchups",
    "generate_dataset",
    "LeagueDatasetConfig",
    "LeagueDatasetResult",
    "LeaguePlayerSpec",
    "collect_league_dataset",
    "OperationRepresentation",
    "clear_representation_cache",
    "representation_for_definition",
    "representation_for_action",
    "representation_for_neural_action",
    "NeuralActionScorer",
    "ContextualNeuralActionScorer",
    "SemanticIdentityNeuralActionScorer",
    "StructuredSemanticCardEncoder",
    "StructuredSemanticV4Scorer",
    "StructuredSemanticV5FusionScorer",
    "StructuredSemanticV5DeckStateScorer",
    "StructuredSemanticV6TacticalActionScorer",
    "SUPPORTED_ARCHITECTURES",
    "build_neural_scorer",
    "migrate_v004_checkpoint_to_deck_state",
    "migrate_v005_deck_state_checkpoint_to_tactical",
    "NeuralModelConfig",
    "NeuralTrainingProfile",
    "NeuralProfile",
    "NeuralPlayer",
    "MACRO_ARCHITECTURE_SCHEMA_VERSIONS",
    "build_neural_player",
    "is_macro_architecture",
    "MacroNeuralPlayer",
    "MACRO_DATASET_SCHEMA_VERSION",
    "MACRO_CANDIDATE_SCHEMA_VERSION",
    "MacroDatasetCampaignConfig",
    "MacroDatasetGenerationResult",
    "generate_macro_dataset",
    "heuristic_macro_selector",
    "MACRO_ARCHITECTURE",
    "MACRO_V2_ARCHITECTURE",
    "MACRO_V3_ARCHITECTURE",
    "MACRO_V4_ARCHITECTURE",
    "MacroActionScorer",
    "MacroActionScorerV2",
    "MacroActionScorerV3",
    "MacroActionScorerV4",
    "macro_candidate_from_dict",
    "MacroEvaluationMetrics",
    "MacroTrainingMetrics",
    "evaluate_macro_epoch",
    "macro_imitation_loss",
    "macro_record_diagnostics",
    "macro_records",
    "unified_record_diagnostics",
    "unified_records",
    "train_macro_epoch",
    "MacroDecisionPayload",
    "AtomicDecisionPayload",
    "DependencyDescriptor",
    "MacroActionRepresentation",
    "PlayTurnCandidate",
    "PlayTurnOutcomeSummary",
    "PlayTurnResolution",
    "PlayTurnSolver",
    "macro_representations_v3",
    "macro_representations_v4",
    "dependency_for_action",
    "HybridPlayer",
    "LegacyActionMiddleware",
    "is_modern_player",
    "DecisionDiagnostic",
    "DeterministicBanishPolicy",
    "HeuristicPlayPolicy",
    "NeuralAcquisitionPolicy",
    "build_composed_player",
    "build_hybrid_player",
    "DEFAULT_HYBRID_PROFILE_DIR",
    "HybridProfile",
    "load_hybrid_profile",
    "AlgorithmicPlayPolicy",
    "PlayCardClassification",
    "load_active_training_profile",
    "load_active_neural_profile",
    "load_training_profile",
    "next_training_profile_id",
    "save_training_profile",
    "versioned_training_profiles",
    "TrainingMetrics",
    "EvaluationMetrics",
    "chosen_action_loss",
    "combined_imitation_loss",
    "iter_jsonl_records",
    "evaluate_epoch",
    "normalized_score_regression_loss",
    "observation_from_dict",
    "is_targeted_mercenary_record",
    "pairwise_ranking_loss",
    "seed_training",
    "split_for_game_id",
    "train_epoch",
    "train_jsonl",
    "NeuralActorCritic",
    "PPOTrainingMacroPlayer",
    "PPOTrainingPlayer",
    "PPOUpdateMetrics",
    "RolloutResult",
    "RolloutTransition",
    "choose_opponent",
    "collect_rollout",
    "evaluate_greedy_model",
    "gae_returns",
    "is_monotonic_evaluation_improvement",
    "ppo_update",
    "terminal_reward",
    "weighted_evaluation_score",
    "load_metrics",
    "write_training_report",
]
