from types import MappingProxyType

from .definitions import (
    BLASTER,
    CRYSTAL,
    INFINITY_SHARD,
    SHARD_REACTOR,
    VOID_ASSASSIN,
    ASPIRANT_MAQUIS, CLERC_AUX_SPORES, ERMITE_FONGIQUE, ZELOTE_DES_EPINES,
    CHEVALIER_LE_SHAI, GARDIEN_DE_LA_FORET, SAULE_VENGEUR, OJAS,
    ELEMENTAL_DU_SILLON, RACINE_DE_LA_FORET,
    APOTRE_DES_OMBRES, BRISE_ETHER, ECLAIREUR_SPECTRAL, FLEAU_DES_OMBRES,
    HERITIER_DU_NEANT, SENTINELLE_DES_TENEBRES, ZARA_RA,
    GARDE_MEMOIRE, INITIE_DE_L_ORDRE, LE_GRAND_ARCHITECTE, MOINE_CRYPTOPOING,
    MOINE_DU_PORTAIL, OMNIUS_L_ERUDIT, PIRATE_HERETIQUE, PROPHETE_DE_LECLAT,
    VOYANTE_DE_VOLONTE,
    DRONE_KILN, DRONE_REACTEUR, DRONES_MINIERS, LEGIONNAIRE_KORVUS,
    VALKYRIE_DES_LANDES,
    ADDITRI_GAIAMENCIENNE, LI_HIN_LA_BRISEE, ZEN_CHI_SET,
    IA_SYSTEMA, GIGA_ADEPTE_DE_LA_SOURCE, ZETTA_L_ENCODEUSE,
    PRIMUS_PILUS, DRONES_NUMERI, EVOKATUS, BROYEU_OPTIO, DRAKONARIUS,
    GENERAL_DECURION,
)
from .model import CardDefinition

_DEFINITIONS = {
    definition.card_id: definition
    for definition in (
        BLASTER,
        CRYSTAL,
        INFINITY_SHARD,
        SHARD_REACTOR,
        VOID_ASSASSIN, ASPIRANT_MAQUIS, CLERC_AUX_SPORES, ERMITE_FONGIQUE,
        ZELOTE_DES_EPINES, CHEVALIER_LE_SHAI, GARDIEN_DE_LA_FORET,
        SAULE_VENGEUR, OJAS, ELEMENTAL_DU_SILLON, RACINE_DE_LA_FORET,
        APOTRE_DES_OMBRES, BRISE_ETHER, ECLAIREUR_SPECTRAL, FLEAU_DES_OMBRES,
        HERITIER_DU_NEANT, SENTINELLE_DES_TENEBRES, ZARA_RA,
        GARDE_MEMOIRE, INITIE_DE_L_ORDRE, LE_GRAND_ARCHITECTE, MOINE_CRYPTOPOING,
        MOINE_DU_PORTAIL, OMNIUS_L_ERUDIT, PIRATE_HERETIQUE, PROPHETE_DE_LECLAT,
        VOYANTE_DE_VOLONTE,
        DRONE_KILN, DRONE_REACTEUR, DRONES_MINIERS, LEGIONNAIRE_KORVUS,
        VALKYRIE_DES_LANDES,
        ADDITRI_GAIAMENCIENNE, LI_HIN_LA_BRISEE, ZEN_CHI_SET,
        IA_SYSTEMA, GIGA_ADEPTE_DE_LA_SOURCE, ZETTA_L_ENCODEUSE,
        PRIMUS_PILUS, DRONES_NUMERI, EVOKATUS, BROYEU_OPTIO, DRAKONARIUS,
        GENERAL_DECURION,
    )
}

if len(_DEFINITIONS) != 48:
    raise ValueError("Card IDs must be unique")

CARD_CATALOG = MappingProxyType(_DEFINITIONS)


def card_definition(card_id: str) -> CardDefinition:
    try:
        return CARD_CATALOG[card_id]
    except KeyError as error:
        raise KeyError(f"Unknown card ID: {card_id}") from error
